author: 若离QQ：2909998156
# 调试模式，用于寻找错误出现的坐标，默认为false
# 特别提示：调试完成后请记得将debug改为false
# 特别提示：调试完成后请记得将debug改为false
# 特别提示：调试完成后请记得将debug改为false
debug: false
# 推送方式：0：邮件推送；1：qmsg推送；2：待添加更多推送
sendType: 0
# 当且仅当sendType为0时有用，邮箱API的地址
emailApiUrl: 'https://api.ruoli.cc/sendMail'
# 当且仅当sendType为1时有用，qmsg的Key（如需使用请自行更改）
myQmsgKey: ''



#用户组配置
##################################################
# 温馨提示：请仔细注意每个模板是属于哪个任务类型的配置！##
##################################################
users:
  # 第一个用户配置
  # 以下配置为工作日志
  # 这里默认仅适配宜宾学院，其他学校自行修改
 
  # 以下配置为查寝
  # 这里默认仅适配四川信息职业技术学院，其他学校自行修改
  - user:
      # 任务类型（收集：0、签到：1、查寝：2、教师工作日志：3）
      type: 2
      #school 学校全称
      schoolName: 天津城建大学
      #username 学号或者工号
      username: '2112201012'
      #password 密码
      password: 'Ning1314!!'
      # 地址信息
      address: '中国天津市西青区张家窝镇煦园南道'
      #sendKey 当sendType为0时代表邮箱，当sendType为1时代表接收消息的QQ号码
      sendKey: ''
      # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
      #lon 经度
      lon: 117.103225
      #lat 纬度
      lat: 329.098996
      #abnormalReason 反馈信息（这个一般不用配置，但是不能删除，删除会报错）
      abnormalReason: ''
      #photo 签到照片，不需要可不填，或者直接删除
      